### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by parzivail** [iChun/Clef#1] opened 2017-08-08 15:30 UTC
I can't find the gradle runners. Am I doing something wrong?

**Comment by superninjakiwi** [comment] 2017-08-08 18:02
Hello Parzivail

It seems you're experiencing a common issue that occurs when the mod doesn't actually exist yet. This is caused by the mod not yet being created, which does indeed cause there to be a lack of gradle runners.  The best way to resolve this issue is to advance forward to a point in time when the mod exists. 

I'm going to suggest that someone label this as Not a bug, as this behavior is expected of the mod in its current state.

Did this solve your problem? Let us know by sending toenail clippings in a bag made of dwarf-hide to the nearest black hole.

**Comment by iChun** [comment] 2017-08-09 01:54
There's no "Not a bug" label so I'm gonna just mark this as invalid.

**Comment by wasdennnoch** [comment] 2017-08-09 12:42
You can always create a label called like that ;)

**Comment by iChun** [comment] 2017-08-17 15:24
Should be fixed now.

**Closed as completed by iChun** 2017-08-17 15:24 UTC
Labels: invalid
